In [1]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
X = [[ 1,  2,  3],  # 2 samples, 3 features
     [11, 12, 13]]
y = [0, 1]  # classes of each sample
clf.fit(X, y)


RandomForestClassifier(random_state=0)

In [2]:
y

[0, 1]

In [3]:
clf.predict(X)

array([0, 1])

In [4]:
clf.predict([[4, 5, 6], [14, 15, 16]])

array([0, 1])

In [6]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate

In [7]:
X, y = make_regression(n_samples=1000, random_state=0)
lr = LinearRegression()

In [8]:
head(X)

NameError: name 'head' is not defined

In [9]:
y.shape

(1000,)

In [10]:
X.shape

(1000, 100)

In [11]:
result = cross_validate(lr, X, y)  # defaults to 5-fold CV
result['test_score']  # r_squared score is high because dataset is easy

array([1., 1., 1., 1., 1.])